### ISSUE TITLE
Metadata not exported

### ISSUE THREAD

**Issue by Rasfuranku** [metaplex-foundation/js-deprecated#41]
Any reason why Metadata is not exported in version 3?

**Comment by kurpav** [comment]
Hi @Rasfuranku 
There were breaking changes in the exports. Now you have to export Metadata from `programs.metadata`.
```ts
import { programs } from '@metaplex/js';
const { metadata: { Metadata } } = programs;

// Metadata
const metadata = await Metadata.load(connection, '<pubkey>');
```

You can also find updated examples in the README.

**Comment by monomadic** [comment]
No, he's right. `Metadata` is not exported because `programs` inside `@metaplex/js` no longer exports `programs`.

I'd suggest downgrading to `4.1.0` and in future upgrade very carefully until they can sort out a proper CI/CD process.

**Comment by AlberErre** [comment]
Yep, seems like exports are removed from the current version. As @monomadic pointed out, we should downgrade to `4.1.0` until they export them correctly (assuming they still want to export them on this package).
